version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/gin-gonic/gin
    versions:
    - 1.6.3
    - 1.7.0
